# Generated by Django 6.0.1 on 2026-04-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='message_id_hash',
            field=models.CharField(editable=False, max_length=255, null=True, unique=True),
        ),
    ]
